Repository PF-Ide-Pintureria/pinturas-app-back, pull requests merged in 2023-07, with the labels that each got.

#35 fixing proxy problems and configuring node version in package.json
  package-lock.json
  package.json
  src/app.js
  src/public/favicon.ico
  src/routes/index.js
Labels: bug, dependencies

#36 Correccion cloudinary edit product
  package-lock.json
  package.json
  src/handlers/createProductHandler.js
  src/handlers/editProductHandler.js
  src/middlewares/multerStorage.js
  src/services/cloudinary.js
  src/services/index.js
Labels: bug, duplicate, help wanted, dependencies

#37 model user terminado y ruta register
  src/controllers/index.js
  src/controllers/registerUserController.js
  src/controllers/resetDBController.js
  src/handlers/index.js
  src/handlers/registerUserHandler.js
  src/models/Review.js
  src/models/Users.js
  src/routes/index.js
Labels: enhancement
